compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

# Cloudflare R2 Media Object Storage Binding
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "mistygreens-media"
